added genric contract call
maticnetwork/polygon-rosetta pull request #10
Opened 2021-12-14 14:43 UTC by Arpan-pujara

2021-12-14 22:13 UTC, roberto-bayardo requested changes

2021-12-14 22:13 UTC, roberto-bayardo commented on services/construction/preprocess.go
> +		preprocessOutputOptions.Value = big.NewInt(0) // MATIC value is 0 when sending ERC20
update the comment (this is no longer processing ERC20 transfers).  Also are we sure we never need to send MATIC with any of our contract invocations?

2021-12-14 22:13 UTC, roberto-bayardo commented on services/construction/preprocess.go
> +func constructcontractCallData(methodSig string, methodArgs []string) ([]byte, error) {
Can you capitalize the "c" in "contract" in this method name to make it proper camel case?

2021-12-14 22:13 UTC, roberto-bayardo commented on services/construction/preprocess.go
> +	splitSigByAnotherParanth := strings.Split(splitSigBypranthesis[1], ")")
this will panic if L268 returns an array of size < 2

2021-12-14 22:13 UTC, roberto-bayardo commented on services/construction/preprocess.go
> +		if v == "address" {
might be more clear using "switch" ... do we want each case to fall through? (E.g. if v=="address" the remaining cases won't match anyway...)

2021-12-15 21:09 UTC, andrewkmin commented on services/construction/preprocess.go
> +	splitSigBypranthesis := strings.Split(methodSig, "(")
If we're going with this convention, can we maybe rename this to `splitSigByLeadingParenthesis`?

2021-12-15 21:09 UTC, andrewkmin commented on services/construction/preprocess.go
> +	splitSigByAnotherParanth := strings.Split(splitSigBypranthesis[1], ")")
And this one to `splitSigByTrailingParenthesis`?

2021-12-15 21:15 UTC, andrewkmin commented on services/construction/utils.go
> +	hash.Write(transferFnSignature)
+1 on declaring that signature as a constant

2021-12-22 15:50 UTC, Arpan-pujara commented on services/construction/utils.go
> +	res := bytes.Compare(methodID, transfetMethodID)
updated

2021-12-22 20:48 UTC, lorines requested changes
Could we please add unit tests? A couple existing unit tests are also failing.

2021-12-22 20:50 UTC, lorines commented on services/construction/parse.go
> +	if hasData(tx.Data) && hasTransferData(tx.Data) {
We also need a case for contract calls

```
if hasTransferData(tx.Data) {
  existing code
} else if hasData(tx.Data) && ! hasTransferData(tx.Data) {
  new code for contract call data
}
```

2021-12-22 22:33 UTC, lorines commented on services/construction/preprocess.go
> -	if v, ok := request.Metadata["gas_price"]; ok {
Why are we getting rid of this? It might be nice to provide a custom gas price

2021-12-22 22:37 UTC, lorines commented on services/construction/payloads.go
> +	} else if hasTransferData(metadata.Data) {
We'd also want to validate contract calls.

2022-01-04 15:28 UTC, lorines commented on services/construction/parse.go
> +	if hasData(tx.Data) && hasTransferData(tx.Data) {
Ignore my comment above.

2022-01-04 17:49 UTC, lorines commented on services/construction/payloads.go
> +	} else if hasTransferData(metadata.Data) {
Let's just add a TODO comment for now

2022-01-04 17:51 UTC, lorines commented on services/construction/parse.go
> +	if hasData(tx.Data) && hasTransferData(tx.Data) {
Just add a TODO comment for now

2022-01-06 15:24 UTC, lorines commented on services/construction/preprocess.go
> +		preprocessOutputOptions.TokenAddress = contractAddress
We should probably rename `TokenAddress` to ContractAddress and then update https://github.com/maticnetwork/polygon-rosetta/blob/master/services/construction/metadata.go#L74

2022-01-14 18:47 UTC, lorines commented on services/construction/preprocess.go
> +		contractAddress, ok := request.Metadata["contract_address"].(string)
Since `contract_address` and `toOp` are the same value, should we just use `toOp`? 
What do you think @Arpan-pujara

2022-01-18 18:32 UTC, lorines commented on services/construction/preprocess.go
> +	fmt.Println(marshaled)
nit: leftover Println

2022-01-18 18:33 UTC, lorines commented on services/construction/preprocess.go
> +	fmt.Println(splitSigByComma)
leftover Println

2022-01-18 18:34 UTC, lorines commented on services/construction/preprocess.go
> +				fmt.Println("in bool case")
leftover Println

2022-01-18 18:34 UTC, lorines commented on services/construction/preprocess.go
> +	fmt.Println("final data:", data)
leftover Println

2022-01-21 20:36 UTC, lorines commented on services/construction/preprocess_test.go
> +					"contract_address": preprocessTokenContractAddress,
This test is failing. This line should be `"contract_address": preprocessToAddress,`

2022-01-21 20:37 UTC, lorines commented on services/construction/preprocess_test.go
> +			operations: templateOperations(preprocessTransferValue, polygon.Currency),
Let's add a case where `preprocessTransferValue` is `0`

2022-01-25 16:05 UTC, lorines commented on services/construction/preprocess.go
> +		fmt.Println("value one...!!!", valueOne)
@Arpan-pujara there are some print statements left

2022-01-25 16:20 UTC, lorines submitted a review, later dismissed

2022-01-25 17:07 UTC, roberto-bayardo approved these changes
mostly just some nitpicks :)

2022-01-25 17:07 UTC, roberto-bayardo commented on services/construction/utils.go
> +	if _, err := hash.Write(fnSignature); err != nil {
I'm not sure it's worth propagating this error since it should never happen. Might be best to just assertion check that it's non-nil and remove error from the return arguments.

2022-01-25 17:07 UTC, roberto-bayardo commented on services/construction/preprocess.go
> +	splitSigByComma := strings.Split(splitSigByTrailingParenthesis[0], ",")
Right after this line I'd check that the number of methodArgs matches the number of args you get from this split to make sure the right # of args has been specified.

2022-01-25 17:07 UTC, roberto-bayardo commented on services/construction/preprocess.go
> +	var isContractCall bool = false
more idiomatic:
```suggestion
	isContractCall := false
```

2022-01-26 08:22 UTC, Arpan-pujara commented on services/construction/types.go
> +	if len(o.ContractAddress) > 0 {
here contractAddress, tokenAddress all the variables used in if() is because they are optional like if its ERC20 tx then there will be tokenAddress, if generic contract call then there methodSig or methodArgs and contractAddress. there will be case when there wont be contractAddress variable present(native currency and token transfer) that why used if for optional

2022-01-26 08:22 UTC, Arpan-pujara commented on services/construction/utils.go
> +	if _, err := hash.Write(fnSignature); err != nil {
what to do in case the error is non-nil?

2022-01-26 15:14 UTC, roberto-bayardo commented on services/construction/utils.go
> +	if _, err := hash.Write(fnSignature); err != nil {
log.fatal ?

2022-01-26 15:15 UTC, roberto-bayardo commented on services/construction/types.go
> +	if len(o.ContractAddress) > 0 {
even without the if you're just assigning an empty string to an empty string, so it will be treated just the same (and omitted from the json as optional)

2022-01-26 15:59 UTC, roberto-bayardo approved these changes

2022-01-26 16:21 UTC, merged