Adding EIP-1559 Support for Tx Construction
maticnetwork/polygon-rosetta pull request #31
Opened 2022-06-03 16:30 UTC by ash-krishnan

With EIP-1559, transaction fees are calculated using (baseFee + priority tip) * gas limit instead of gas price * gas limit.
In metadata, we fetch base fee from the latest block. And we use our new client function  `SuggestGasTip` which calls RPC endpoint `eth_maxPriorityFeePerGas` to fetch the priority tip. Gas limit stays unchanged. We set gas price to zero because we don't need it to construct dynamic fee transactions, because we are dropping support of constructing legacy transactions. But we still need gas price in the data API because we still need to be able to read/parse legacy transactions.

Gas Cap can be overridden with user input but by default it is (baseFee * 2 + priority tip). 

We have also changed the signer we previously use (EIP-155Signer, which only supports legacy transactions) to the LondonSigner, which supports dynamic fee transactions.

In SendTransaction, dynamic fee transaction will only successfully broadcast if we remove the first two bytes of the transaction data, more information here: https://ethereum.stackexchange.com/questions/124447/eth-sendrawtransaction-with-dynamicfeetx-returns-expected-input-list-for-types

2022-06-03 17:05 UTC, andrewkmin commented on services/construction/types.go
> +	gasPrice := big.NewInt(0)
qq: any particular reason we're manually setting `gasPrice` to 0 here?

2022-06-03 17:08 UTC, andrewkmin commented on polygon/client.go
> +	// We have to remove the first two bytes otherwise DynamicFeeTxs will not send:
Thanks for this context 🙏

2022-06-03 17:09 UTC, andrewkmin commented on polygon/client.go
> +//func (ec *Client) GetFeeHistory(ctx context.Context) (*big.Int, error) {
Maybe we can table this as a follow up item/alternative method if we need more "up-to-date" estimates

2022-06-03 17:15 UTC, andrewkmin commented on services/construction/metadata.go
> +	// gasPrice, err := a.client.SuggestGasPrice(ctx, input.GasPrice)
Do we want to use the live estimate here?

2022-06-03 18:16 UTC, ash-krishnan commented on services/construction/types.go
> +	gasPrice := big.NewInt(0)
GasPrice isn't used by Dynamic Fee txs. So we can get the live estimate and set in the unsigned transaction. But in `combine.go` we can't set Gas Price in the dynamic tx fee struct: (https://github.com/maticnetwork/polygon-rosetta/blob/7075fdf80566b8b2a3328b47a3d56b1f19d1efbf/services/construction/combine.go#L46). So when the signed transaction has no gas price. We also don't use it in our calculations so we're also making extra RPC calls for information we're not using.

2022-06-03 18:16 UTC, ash-krishnan commented on polygon/client.go
> +//func (ec *Client) GetFeeHistory(ctx context.Context) (*big.Int, error) {
Yup, forgot to remove this, I'll get rid of it

2022-06-03 18:17 UTC, ash-krishnan commented on services/construction/metadata.go
> +	// gasPrice, err := a.client.SuggestGasPrice(ctx, input.GasPrice)
We're not really using gas price anymore in the construction API so getting live estimates might be unnecessary here. We also can't set gas price in the dynamic fee tx in `combine.go`.

2022-06-05 16:04 UTC, roberto-bayardo requested changes
Most suggestions are around blowing away more of the legacy GasPrice code (if it's possible, which it seems it should be)

2022-06-05 16:04 UTC, roberto-bayardo commented on services/construction/types.go
>  	GasPrice string `json:"gas_price"`
Can this be removed entirely now that we don't construct old type txs?

2022-06-05 16:04 UTC, roberto-bayardo commented on services/construction/preprocess.go
>  	// Override gas_price
can we get rid of this? Overriding gas price shouldn't do anything if we construct only 1559 type transactions right?

2022-06-05 16:04 UTC, roberto-bayardo commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
can we get rid of this?

2022-06-05 16:04 UTC, roberto-bayardo commented on services/construction/types.go
>  	GasPrice        string   `json:"gas_price,omitempty"`
same .. get rid of this if never going to be used anymore?

2022-06-06 19:45 UTC, ash-krishnan commented on services/construction/types.go
>  	GasPrice string `json:"gas_price"`
like it looks like gas price is still being used here? https://github.com/maticnetwork/polygon-rosetta/blob/c082aa44e76690a59c6fdc31868c058360e856e2/polygon/client.go#L376 or is the `transaction` struct just being used in construction

2022-06-06 21:16 UTC, roberto-bayardo commented on services/construction/types.go
>  	GasPrice string `json:"gas_price"`
that gasPrice is just a local variable initialized by calling EffectiveGasPrice.   Yeah I was thinking the structs might just be part of construction. (I could be wrong though ...)

2022-06-07 16:31 UTC, ash-krishnan commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
could we get a confirmation that removing `gas_price` in the `transaction` and `option` structs and generally from construction will not affect block/transaction parsing?

2022-06-07 16:48 UTC, andrewkmin commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
one scenario i could envision is if we ever want/need to manually pass in a super high gas price, likely to be used with a legacy transaction. this is what nova currently does for ETH's replacement transactions (use 1559 by default, but legacy for replacements). however, if that seems pointless, then we could remove `gas_price` here

the TLDR of the above ^ is: will EIP1559 ever put us into a place where we're unable to send a tx through with high urgency?

2022-06-07 17:21 UTC, roberto-bayardo commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
That can be accomplished by setting a very high miner tip.   I don't think there's any reason to be creating legacy transactions as 1559 is equal or better in every dimension.

2022-06-07 23:06 UTC, ash-krishnan commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
agreed we can create an override for the priority tip to be set in preprocess like we were doing for `gas_price`. in that case, should i remove `gas_price`?

2022-06-07 23:40 UTC, roberto-bayardo commented
If it doesn't break anything I would highly recommend it!

2022-06-07 23:41 UTC, roberto-bayardo commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
If it doesn't break anything I would recommend it!  Ok w/ you @andrewkmin ?

2022-06-08 19:14 UTC, ash-krishnan commented on services/construction/types.go
>  	GasPrice        *big.Int `json:"gas_price,omitempty"`
Cool, the `block` endpoint still works fine so I'll take it out

2022-06-13 10:28 UTC, VAIBHAVJINDAL3012 approved these changes

2022-06-13 10:42 UTC, merged